version: "3.8"

services:
  mongodb-ebalance:
    container_name: mongodb-ebalance
    image: mongo
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./mongodb/data:/data/db
      - ./mongodb/init/:/docker-entrypoint-initdb.d/:ro
    ports:
      - 27017:27017
    restart: unless-stopped
  clickhouse-ebalance:
    image: yandex/clickhouse-server
    ports:
      - 8123:8123
    volumes:
      - ./clickhouse/data:/var/lib/clickhouse
      - ./clickhouse/init/:/docker-entrypoint-initdb.d/:ro
